log_errors = On
error_log = /proc/self/fd/2
upload_max_filesize = 128M
post_max_size = 128M
max_execution_time = 300
memory_limit = 512M
max_input_vars = 10000
opcache.interned_strings_buffer = 32
sendmail_path = "/usr/bin/msmtp -t"